# Generated by Django 4.1.6 on 2023-05-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Позиция в списке')),
                ('subtitle', models.CharField(blank=True, max_length=180, null=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/elements/', verbose_name='картинка')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Коэфф для расчета ')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Позиция в списке')),
                ('subtitle', models.CharField(blank=True, max_length=180, null=True, verbose_name='Подзаголовок')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Коэфф для расчета ')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Позиция в списке')),
                ('subtitle', models.CharField(blank=True, max_length=180, null=True, verbose_name='Подзаголовок')),
                ('default_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.option')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='category',
            field=models.ManyToManyField(to='calc.optionscategory'),
        ),
    ]
