# Generated by Django 4.1.6 on 2023-03-07 16:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/elements/', verbose_name='картинка')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Мета title')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Коэфф для расчета ')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Ссылка')),
                ('round_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Круглая картинка для навигации')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/options/', verbose_name='картинка для слайдера')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Мета title')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Коэфф для расчета ')),
                ('Parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.parameter')),
            ],
        ),
    ]
