# Generated by Django 4.1.6 on 2023-05-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_element_subtitle_alter_option_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='coefficient',
        ),
        migrations.AddField(
            model_name='option',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена за м2 '),
        ),
    ]
