# Generated by Django 4.1.6 on 2023-05-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_remove_option_coefficient_option_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='slug',
            field=models.SlugField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='slug',
            field=models.SlugField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='optionscategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена '),
        ),
    ]
