# Generated by Django 4.1.6 on 2023-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_element_slug_option_slug_optionscategory_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDimentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('depth', models.IntegerField(blank=True, null=True, verbose_name='Глубина')),
            ],
        ),
    ]
