# Generated by Django 4.1.6 on 2023-05-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_basicdimentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdimentions',
            name='shelf_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота полок'),
        ),
        migrations.AlterField(
            model_name='basicdimentions',
            name='depth',
            field=models.IntegerField(blank=True, choices=[(500, '500'), (600, '600')], null=True, verbose_name='Глубина'),
        ),
    ]
